// Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/awslabs/amazon-kinesis-firehose-for-fluent-bit/firehose (interfaces: FirehoseClient)

// Package mock_firehose is a generated GoMock package.
package mock_firehose

import (
	reflect "reflect"

	firehose "github.com/aws/aws-sdk-go/service/firehose"
	gomock "github.com/golang/mock/gomock"
)

// MockFirehoseClient is a mock of FirehoseClient interface
type MockFirehoseClient struct {
	ctrl     *gomock.Controller
	recorder *MockFirehoseClientMockRecorder
}

// MockFirehoseClientMockRecorder is the mock recorder for MockFirehoseClient
type MockFirehoseClientMockRecorder struct {
	mock *MockFirehoseClient
}

// NewMockFirehoseClient creates a new mock instance
func NewMockFirehoseClient(ctrl *gomock.Controller) *MockFirehoseClient {
	mock := &MockFirehoseClient{ctrl: ctrl}
	mock.recorder = &MockFirehoseClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFirehoseClient) EXPECT() *MockFirehoseClientMockRecorder {
	return m.recorder
}

// PutRecordBatch mocks base method
func (m *MockFirehoseClient) PutRecordBatch(arg0 *firehose.PutRecordBatchInput) (*firehose.PutRecordBatchOutput, error) {
	ret := m.ctrl.Call(m, "PutRecordBatch", arg0)
	ret0, _ := ret[0].(*firehose.PutRecordBatchOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutRecordBatch indicates an expected call of PutRecordBatch
func (mr *MockFirehoseClientMockRecorder) PutRecordBatch(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutRecordBatch", reflect.TypeOf((*MockFirehoseClient)(nil).PutRecordBatch), arg0)
}
